"""Add description, goal, and level to plans table

Revision ID: add_plan_fields
Revises:
Create Date: 2024-02-09 21:16:00.000000

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'add_plan_fields'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', 'description', sa.String(length=1000), nullable=True)
    op.add_column('plans', 'goal', sa.String(length=50), nullable=False)
    op.add_column('plans', 'level', sa.String(length=20), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plans', 'level')
    op.drop_column('plans', 'goal')
    op.drop_column('plans', 'description')
    # ### end Alembic commands ###
