"""Initial schema

Revision ID: 001_initial
Revises:
Create Date: 2024-02-09 21:17:00.000000

"""
from collections.abc import Sequence
from typing import Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '001_initial'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Create roles table
    op.create_table('roles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.Column('description', sa.String(), nullable=True),
        sa.Column('is_paid', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint('pk_roles'),
        sa.UniqueConstraint('uq_roles_name')
    )

    # Create users table
    op.create_table('users',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('role_id', sa.Integer(), nullable=True),
        sa.Column('coach_id', sa.UUID(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['role_id'], 'roles', ['id'], ),
        sa.ForeignKeyConstraint(['coach_id'], 'users', ['id'], ),
        sa.PrimaryKeyConstraint('pk_users'),
        sa.UniqueConstraint('uq_users_email')
    )

    # Create exercises table
    op.create_table('exercises',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('instructions', sa.Text(), nullable=True),
        sa.Column('muscle_groups', sa.JSON(), nullable=True),
        sa.Column('equipment', sa.JSON(), nullable=True),
        sa.Column('movement_type', sa.String(length=50), nullable=True),
        sa.Column('position', sa.String(length=50), nullable=True),
        sa.Column('contraction_type', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('coach_id', sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(['coach_id'], 'users', ['id'], ),
        sa.PrimaryKeyConstraint('pk_exercises')
    )

    # Create plans table with new fields
    op.create_table('plans',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.String(length=1000), nullable=True),
        sa.Column('goal', sa.String(length=50), nullable=False),
        sa.Column('level', sa.String(length=20), nullable=False),
        sa.Column('coach_id', sa.UUID(), nullable=True),
        sa.Column('duration_weeks', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['coach_id'], 'users', ['id'], ),
        sa.PrimaryKeyConstraint('pk_plans')
    )

    # Create workout_sessions table
    op.create_table('workout_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('plan_id', sa.Integer(), nullable=True),
        sa.Column('client_id', sa.UUID(), nullable=True),
        sa.Column('date', sa.Date(), nullable=True),
        sa.Column('completed', sa.Boolean(), nullable=True),
        sa.Column('notes', sa.String(), nullable=True),
        sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
        sa.Column('updated_at', sa.TIMESTAMP(), nullable=True),
        sa.ForeignKeyConstraint(['plan_id'], 'plans', ['id'], ),
        sa.ForeignKeyConstraint(['client_id'], 'users', ['id'], ),
        sa.PrimaryKeyConstraint('pk_workout_sessions')
    )

    # Create workout_exercises table
    op.create_table('workout_exercises',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.Integer(), nullable=True),
        sa.Column('exercise_id', sa.Integer(), nullable=True),
        sa.Column('sets_planned', sa.Integer(), nullable=True),
        sa.Column('reps_planned', sa.String(), nullable=True),
        sa.Column('weight_planned', sa.String(), nullable=True),
        sa.Column('rest_between_sets', sa.String(), nullable=True),
        sa.Column('sets_done', sa.Integer(), nullable=True),
        sa.Column('reps_done', sa.JSON(), nullable=True),
        sa.Column('weight_used', sa.String(), nullable=True),
        sa.Column('time_spent', sa.String(), nullable=True),
        sa.Column('reps_in_time', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], 'workout_sessions', ['id'], ),
        sa.ForeignKeyConstraint(['exercise_id'], 'exercises', ['id'], ),
        sa.PrimaryKeyConstraint('pk_workout_exercises')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workout_sessions')
    op.drop_table('plans')
    op.drop_table('exercises')
    op.drop_table('users')
    op.drop_table('roles')
    # ### end Alembic commands ###
